### ISSUE TITLE
[Issue tracker/Sammelissue] Ideas for improvement

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/RadioDroid#18]
Here's my list in form of a check list (see syntax `[ ]` and `[X]` for checkboxes when you edit the thread posting). I marked some of them which I think are implemented in RadioDroid2 and/or which issue number the item already has.

- [ ] #231 make search function _suggests as you type_ (after entering 2..3 characters)
- [ ] #232 add user option "Low bitrate streams only"
- [ ] #33 add "Favorites" export/import function (similar to #132)
- [ ] #132 export starred stations as playlist (similar to #33)
- [ ] #232 add privacy option opt-in "allow the server to count my station play click"
- [ ] #102 Increasing alarm volume
- [ ] #127 add a Play/Pause/Stop-Button on top of the screen

**Comment by Wikinaut** [comment]
just a quick feedback to you: the RadioDroid2 works perfectly: no stream interruptions (loss of connections...) anymore!

**Comment by Wikinaut** [comment]
added "make Favorite list default start Tab" to the list above

**Comment by Wikinaut** [comment]
added #27 to the  to do list

**Comment by segler-alex** [comment]
why did you add something, i already added and published today ?????????

**Comment by Wikinaut** [comment]
@segler-alex today, the Alarm came, but not the sleep-timer. Or I mixed it up?

**Comment by segler-alex** [comment]
i added both

**Comment by Wikinaut** [comment]
I pulled the Google Play version. Perhaps, this differs from the latest master branch ?

**Comment by segler-alex** [comment]
no it is in the current google branch :)
you have to play a station, and then click the radio browser entry in the message area. a window will open where you can stop the stream. but you can also add a sleep timer

**Comment by Wikinaut** [comment]
Negative.

On my Y201 (Android 4.0.3) I see two icons, barely visible a small clock. When I click onto the clock symbol, a third icon appears (waste basket). Clicking onto the clock: no action

On my P8 LITE (Android 5.0.1), i see only "Stop" in the message area. Nothing happens.

Both are running the latest version from Google Play.

**Comment by Wikinaut** [comment]
And to have the timer action there, I regard this as non-intuitive, sorry. Better to have it close to the play icon, or in the settings, where the alarm can be set: add a setting for an optional time-out (and permanently store the last value, e.g. 15 minutes or so, if it was set, or so.)

**Comment by segler-alex** [comment]
can you make screenshots for both?

**Comment by segler-alex** [comment]
i tested with galaxy s5 (android 6), galaxy s2 (android 2.3) and fairphone 1 (android 4.2.2). and it is working an all of them

**Comment by Wikinaut** [comment]
P8 LITE: I found that I have to click the message itself (this is definitely not intuitive) and I may not click the STOP button. Better add a second button similar to "STOP": "SLEEP"

**Comment by Wikinaut** [comment]
and how can I set 5 minutes, or 15 minutes as sleep timer ? There are some increments à 10 minutes, ah, now I know.

**Comment by Wikinaut** [comment]
Instead of "PlayerInfo" you could think of renaming this view to something like "StopOrSleeptimer"

**Comment by segler-alex** [comment]
the android documentation says that messages HAVE TO be clickable, because older smartphones do not have the possibility to show buttons there. so you must implement all actions in the view that shows when you click the message. the button in the message is just convinience for newer smartphones

**Comment by segler-alex** [comment]
This should be the "PlayerInfo" page. it will grow. i want to add Shoutcast stream info there too.

**Comment by Wikinaut** [comment]
on the Y201, a small 4" devices,  the minutes are not shown on the screen after having clicked the clock, because their position is most likely outside the screen (below the bottom).

**Comment by segler-alex** [comment]
ok, i will check how i can display the text in another way. i am still not happy with this page anyway. it just does not look like material design :(

**Comment by Wikinaut** [comment]
@segler-alex wrote
> the android documentation says that messages HAVE TO be clickable, because older smartphones do not have the possibility to show buttons there. so you must implement all actions in the view that shows when you click the message. the button in the message is just convinience for newer smartphones

I do understand, okay. But why not simply adding a new "sleep timeout" setting ? (in the "Settings")

**Comment by segler-alex** [comment]
a sleep timeout global setting would be "global" but i don't want that. you should be able to add some minutes to the sleep timer fast. and you don't want the same sleep time every time.

**Comment by Wikinaut** [comment]
Are you listening to two different radios with sleep timer(s) at the same time ? this does not make sense.

**Comment by Wikinaut** [comment]
you could have some quick-add buttons: +5 -5 +10 -10 minutes

**Comment by Wikinaut** [comment]
(prepaing screenshots now of the Y201)

**Comment by Wikinaut** [comment]
* Y201 4" Screen

* before clicking the clock icon
<img src="http://i.imgur.com/6gGyqjc.jpg">

* after having clicked the clock icon (take note, that the remaining minutes are invisible)
<img src="http://i.imgur.com/zm66Edj.jpg">

**Comment by segler-alex** [comment]
ok, thanks, i will look at it.

**Comment by Wikinaut** [comment]
(#27 fixed now with https://github.com/segler-alex/RadioDroid/commit/f4705da9824bd2b648d56398d8c3e5c0f68e5afa )

**Comment by Wikinaut** [comment]
added #172 to the list

**Comment by Wikinaut** [comment]
updated the list and removed items which are no longer applicable because they related to the old version of RadioDroid.

**Comment by Wikinaut** [comment]
updated and cleaned the list

**Comment by Wikinaut** [comment]
closing this "Sammelissue" after having set up individual "issues" for the open cases.
